Netflix/spectator-py

setup.py
spectator/registry.py
tests/test_registry.py

Split measurements into max-sized chunks before sending them to our
aggregator cluster. This introduces a new configuration option
`batch_size` that specifies the maximum number of measurements to send
at once.
For python 2.7 compatibility adds 'future' to the `install_requires`
since that's required for the `builtins` module.

Send measurements in batches

---

.travis.yml
tox.ini

Fix #5, users can move to 3.6 if they have trouble with
3.5. We aren't going to spend time debugging it.

remove build for 3.5

---

.travis.yml
tests/test_counter.py
tests/test_http.py
tox.ini

when working with a gzip object, you get bytes, which should be decoded
into a string, before passing it to the json module.
returning the exception directly as an error message from the http
server makes it clear why the test was failing.
this was tested successfully with 2.7.15, 3.5.5 and 3.6.5.

fix tests for python 3.5

---

setup.py
spectator/histogram/percentiles.py
tests/test_percentiles.py

It was broken before because the `_clock` attribute was
not set.

fix PercentileTimer.stopwatch

---

spectator/counter.py
spectator/distsummary.py
spectator/gauge.py
spectator/registry.py
spectator/timer.py
tests/test_registry.py

If an existing meter already exists when creating a new one, the existing one is returned. For example:
```
my_gauge = GlobalRegistry.gauge('test')
test_gauge = GlobalRegistry.gauge('test')
my_gauge == test_gauge # True
```
However, if the second meter requested is of a different type, a meter of the first is returned. For example:
```
my_gauge = GlobalRegistry.gauge('test')
my_counter = GlobalRegistry.counter('test')
my_guage == my_counter # Returns True
my_counter.increment() # Raises exception because it is a gauge and gauges don't have a increment method
```
This PR brings spectator-py closer to parity by returning a Noop meter if a duplicate meterId is used when requesting a different meter type. The new behavior is:
```
my_gauge = GlobalRegistry.gauge('test')
my_counter = …
```

Return a noop meter if a meterId is reused for a different meter type

---

spectator/registry.py

Previously we were ignoring meters with unknown or missing statistic tag
values. Now we match the java/golang behavior of sending those as gauges
by default.

Use a gauge behavior for unknown statistics

---

setup.py
spectator/counter.py
spectator/gauge.py
spectator/id.py
tests/test_counter.py
tests/test_gauge.py

For counters and gauges, the statistic provided on the id
should be used if present. This allows these base types to
be used as a building block for other composite types.

honor existing statistic if present

---

tox.ini

* Checking reStructuredText as a part of setup.py check is deprecated. This
step should now use `twine check dist/*` after the wheel has been built. See
the following link for more details:
https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup
* Restrict `flake8` execution to the `spectator` and `tests` directories, so
that it does not crawl a local virtualenv, if one has been installed.

fix tox testing configuration

---

README.md

We occasionally get a few questions about how to use the spectator-py library
in our support channels. This change copies a bit of descriptive text from the
original Spectator Java library docs and adds some notes specific to Python
usage. In particular, it calls out the correct method of stopping publication
of Gauge values.

add usage guide to readme

---

.travis.yml
README.md
setup.py
tox.ini

We wanted to move up to Python 3.6 as a minimum version, so that we could
start taking advantage of f-strings, but we also want this library to work
with the minimum number of dependencies outside of the system Python 3
provided by our chosen Linux distributions.
The oldest system Python in our base OS collection is 3.5, which won't be
retired until sometime in 2021. The next oldest at that point will be 3.6.

add python 3.5

---

.travis.yml
README.md
spectator/__init__.py
spectator/registry.py

For Python3.7+, improve fork() handling by stopping/starting the registry using 'os.register_at_fork()'

Improve fork() handling

---

spectator/registry.py
tests/test_registry.py

More complete fix for https://github.com/Netflix/spectator-py/pull/43.

allow optional ttl seconds for gauges

---

README.md
setup.py
spectator/sidecarconfig.py
tests/test_sidecarconfig.py

We have a case where we want to disable sending messages to the udp socket
when running integration tests on CI servers which also happen to be running
SpectatorD. The applications under test use the GlobalRegistry liberally.
The SPECTATOR_OUTPUT_LOCATION environment variable may be set to "none" to
disable publishing messages, or "memory" if there is a need to verify the
messages.

add SPECTATOR_OUTPUT_LOCATION environment variable config

---

README.md
setup.py
spectator/protocolparser.py
tests/test_protocolparser.py

This feature is intended to support testing by making it easier to validate
the values captured by a MemoryWriter.

add spectatord line protocol parser

---

README.md
setup.py

This functionality is now covered by the line protocol parser.

remove meter class info from readme

---

README.md
setup.py
spectator/sidecarwriter.py

The previous method of opening a socket during the UdpWriter init and re-using
it for sending packets was not universally usable with asyncio, because the
initial call was blocking, even though the send calls were non-blocking. This
meant that the initial import of the GlobalRegistry from spectator-py needed
to be handled outside of async code, to avoid BlockingIO errors, but otherwise,
metrics data would be sent as expected. This implementation was originally
selected, because it was thought that it performed slightly better than the
alternative.
This commit changes the implementation of the UdpWriter, so that a new socket
is opened within a context manager for every message that is sent to the
SpectatorD sidecar. The context manager ensures that the socket is closed
after the message is …

Improve asyncio support

---

setup.cfg

https://netflix.github.io/atlas-docs/spectator/lang/py/usage/ states: "This library currently targets the Python >= 3.8."
In addition, the test matrix includes 3.8:
https://github.com/stacywsmith/spectator-py/blob/main/.github/workflows/pr.yml#L11
Based on this information, it appears that Python 3.8 was intended to be supported, but accidentally omitted in the python_requires line of setup.cfg.

Change setup.cfg python_requires to allow Python 3.8.

---

setup.cfg
spectator/registry.py
spectator/writer/file_writer.py
spectator/writer/memory_writer.py
spectator/writer/noop_writer.py
spectator/writer/udp_writer.py
tests/writer/test_noop_writer.py

Most users have not found the info level logs related to the Registry or the Writers to be useful. Dropping these logs to debug level.

reduce log levels

---

setup.cfg
spectator/writer/new_writer.py
spectator/writer/udp_writer.py
spectator/writer/unix_writer.py
tests/udp_server.py
tests/unix_server.py
tests/writer/test_new_writer.py
tests/writer/test_unix_writer.py

For the `UdpWriter`, only open the socket once, during initialization. While this has not been an issue in practice, and performs comparably, it leads to port churn on the host that uses this. A single open socket will lead to a single port being used for communication.
The `FileWriter` is not sufficient for communicating with Unix Domain Sockets, and we need to add a `UnixWriter` to handle this correctly. Verified in tests.

fix socket communications

---

setup.cfg
spectator/writer/udp_writer.py
spectator/writer/unix_writer.py

The legacy `GlobalRegistry` will open sockets upon import (`UdpWriter` by default). For applications that spawn a lot of threads, we want to keep this behavior under control, so lazily instantiate the sockets for the `UnixWriter` and the `UdpWriter`. We implement a `threading.Lock` when instantiating the sockets, to help avoid races between threads.

lazily open sockets
